---
title: "Untitled"
output: html_document
date: "2024-06-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#setwd("C:/Länsstyrelseprojektet")
library(tidyverse)
library(rkt)
library(mgcv)
library(jsonlite)
library(curl)
library(zoo)
library(purrr)
library(furrr)
library(gratia)
library(janitor)


rkt_out <- function(rkt){
  tibble(p.value = ifelse(is.na(rkt$sl.corrected)==T, rkt$sl, rkt$sl.corrected), statistic = rkt$S, slope = rkt$B, tau=rkt$tau)
}
```
```{r}
# Negativa värden för meter under ytan, t.ex. 
# 00164942
# 2
# 00158093
# 3
# 00116862
# 4
# 00165077
# 5
# 00165078
# 6
# 00166612
# 7
# 00166622
```


```{r}
#ladda in 7 df
df1 <- read_csv("Indata/data_combined1.csv")[,-1]
df2 <- read_csv("Indata/data_combined2.csv")[,-1]
df3 <- read_csv("Indata/data_combined3.csv")[,-1]
df4 <- read_csv("Indata/data_combined4.csv")[,-1]
df5 <- read_csv("Indata/data_combined5.csv")[,-1]
df6 <- read_csv("Indata/data_combined6.csv")[,-1]
df7 <- read_csv("Indata/data_combined7.csv")[,-1]

stationIDs<-read_csv("Indata/stationsinformation.csv")%>%select(platsbeteckning, provplatsid)

data_combined <- rbind(df1, df2, df3, df4, df5, df6, df7) 


#lägger till en column med seriens längd i år, samt år som behövs för filtrering. Alla grundvattennivåer görs negativa för att positiva trender ska motsvara en ökning.
data_combined <- data_combined%>%left_join(stationIDs)%>%
  rename(ID=provplatsid)%>%group_by(ID)%>%
  mutate(year=year(obsdatum), serie_langd = max(year) - min(year), grundvattenniva_m_u_markyta=-grundvattenniva_m_u_markyta)%>%ungroup()%>%select(-platsbeteckning)

#Ta bort första årets värden från alla serier.
id_remove <- data_combined%>%filter(metod_for_matning == "klucklod")%>%group_by(ID)%>%filter(year(obsdatum) == min(year(obsdatum)))%>%pull(rowid)
data_combined <- data_combined%>%filter(!rowid %in% id_remove)

#Samma för logger värdena
id_remove <- data_combined%>%filter(metod_for_matning == "logger")%>%group_by(ID)%>%filter(year(obsdatum) == min(year(obsdatum)))%>%pull(rowid)
data_combined <- data_combined%>%filter(!rowid %in% id_remove)

#Ta bort alla misstänkta felvärden från data
id_remove1 <- data_combined%>%filter(nivaanmarkning == "misstänkt felvärde" | nivaanmarkning == "påverkat av test")%>% 
# nivaanmarkning == "under mätgräns" | nivaanmarkning == "över mätgräns")%>% 
  
  pull(rowid)
data_combined <- data_combined%>%filter(!rowid %in% id_remove1)

#Ta bort tidig data i serier med stora glapp. Stort glapp = 10 år
#Identifiera första året för loggern (-3 eftersom det ofta gjordes klucklodsmätningar precis i början av nyinsatt logger) 
data_combined%>%select(ID, metod_for_matning, year)%>%
  group_by(ID)%>%
  filter(metod_for_matning=="logger")%>%summarize(first_year_logger=min(year)-3)->first_years

#Identifiera stationer med ett glapp av minst 10 år
data_combined%>%select(ID, metod_for_matning, year)%>% 
  left_join(first_years)%>%
              filter(!(metod_for_matning=="klucklod" & year >=first_year_logger))%>%
  group_by(ID, metod_for_matning)%>%
  summarize(first_year=min(year), last_year=max(year))%>%
  pivot_wider(names_from =metod_for_matning, values_from = c(first_year, last_year))%>%
  filter(first_year_logger - last_year_klucklod>=10)%>%pull(ID)->stations_with_gap

#Ta bort klucklodsmätningar för serier med långa glapp
data_combined <- data_combined%>%filter(!(ID %in% stations_with_gap & metod_for_matning=="klucklod"))


#plockar ut medianvärde per station och dag
data_logger<-data_combined%>%
  filter(metod_for_matning=="logger")%>%
  group_by(ID)%>%
  filter(max(year(obsdatum)) - min(year(obsdatum))>= 6)%>%
  ungroup()%>%
  mutate(obsdatum1=ymd_hms(obsdatum), date=as.Date(obsdatum1),day=day(obsdatum1), hour=hour(obsdatum1))%>%
  group_by(ID, date)%>%summarize(median_level=median(grundvattenniva_m_u_markyta, na.rm = T)) #Varnar för att datumen inte delas upp korrekt

data_logger <- na.omit(data_logger) #Här tar jag bort rader med NA, vet ej ifall det är en bra lösning men det är för tillfället nödvändigt när alla stationer körs.

#Månadsmedelvärde per station baserat på medianvärde per dag under månaden
data_logger%>% select(ID, date)%>%arrange(ID, date)%>%
  group_by(ID)%>%
  expand(., date = seq.Date(min(date, na.rm = T), max(date, na.rm = T), 1))%>%
  full_join(data_logger)%>%
  mutate_at("median_level",na.approx, maxgap=40)->data_complete_logger

  data_complete_logger%>%
    mutate(month=month(date), year=year(date))%>%
  group_by(ID,year, month)%>%
  summarize(mean_level_month=median(median_level, na.rm=T))->data_monthly_logger

#Månadsmedelvärde per station, här har inget medianvärde per dag beräknats först. Anledning: finns bara en-två mätningar per månad
data_combined%>%
  filter(serie_langd >= 10)%>%
  filter(metod_for_matning=="klucklod")%>%
  mutate(obsdatum1=ymd_hms(obsdatum), date=as.Date(obsdatum1),day=day(obsdatum1))%>%
  filter(day>7 & day <23)%>%
#bara dagar mellan 8e och 22a i månaden "räknas" till den aktuella månaden. Resterande filtreras bort.
    mutate(month=month(date), year=year(date))%>%
  group_by(ID,year, month)%>%
  summarize(mean_level_month=mean(grundvattenniva_m_u_markyta))->data_monthly_lod
  #mutate(month = case_match(month, 1 ~ "januari", 2 ~ "februari", 3 ~ "mars", 4~"april", 5~"maj", 6~"juni", 7~ "juli", 8~"augusti", 9~"september", 10~"oktober", 11~"november", 12~"december" ))->data_monthly_lod

#Hitta överlapp mellan lod och logger och använd bara logger data för den tiden.
row.names(data_monthly_lod)<-paste(data_monthly_lod$ID, data_monthly_lod$year, data_monthly_lod$month)
row.names(data_monthly_logger)<-paste(data_monthly_logger$ID, data_monthly_logger$year, data_monthly_logger$month)
duprows <- rownames(data_monthly_lod) %in% rownames(data_monthly_logger)

#Sortera månaderna i rätt ordning
rbind(data_monthly_logger%>%mutate(metod="logger"),data_monthly_lod[!duprows,]%>%mutate(metod="klucklod"))%>%
  mutate(month = case_match(month, 1 ~ "januari", 2 ~ "februari", 3 ~ "mars", 4~"april", 5~"maj", 6~"juni", 7~ "juli", 8~"augusti", 9~"september", 10~"oktober", 11~"november", 12~"december"))%>%
  pivot_wider(names_from= month, values_from=mean_level_month)%>% 
  arrange(ID, year)%>%
  select(ID,metod, year, januari, februari, mars, april, maj, juni, juli, augusti, september, oktober, november, december) ->data_monthly

#Använd bara lodade data om det finns en observation varje monat, dvs 12 månatliga värden.
data_monthly_lod%>%mutate(metod="klucklod")%>%
  group_by(ID, year)%>%filter(n()==12)%>% 
  summarize(median_level_annual=median(mean_level_month, na.rm=T))%>%
  ungroup()->data_annual_lod


data_complete_logger%>%
  mutate( month=month(date), year=year(date), day=day(date))%>%
  group_by(ID,year)%>%
  summarize(median_level_annual=median(median_level, na.rm = TRUE))%>%
  mutate(metod="logger")->data_annual_logger

row.names(data_annual_lod)<-paste(data_annual_lod$ID, data_annual_lod$year)
row.names(data_annual_logger)<-paste(data_annual_logger$ID, data_annual_logger$year)
duprows <- rownames(data_annual_lod) %in% rownames(data_annual_logger)

 data_annual_logger%>% full_join(data_annual_lod[!duprows,]%>%mutate(metod="klucklod"))%>%
  arrange(ID, year)->data_annual 

#Minimum och maximum årliga värden, använd alla lodade data inte bara mellan dag 8 och 23. 
#########################################################################################
data_combined%>%
  filter(serie_langd >= 10)%>%
  filter(metod_for_matning=="klucklod")%>%
  mutate(obsdatum1=ymd_hms(obsdatum), date=as.Date(obsdatum1),day=day(obsdatum1))%>%
  mutate(month=month(date), year=year(date))%>%
  #group_by(ID,year, month)%>%
  #summarize(min_level_month=min(grundvattenniva_m_u_markyta, na.rm=T),
  #          max_level_month=max(grundvattenniva_m_u_markyta, na.rm=T))%>%
  group_by(ID, year)%>%#filter(n()==12)%>%
  summarize(min_level=min(grundvattenniva_m_u_markyta, na.rm=T), 
            max_level=max(grundvattenniva_m_u_markyta, na.rm=T),
            q05=quantile(grundvattenniva_m_u_markyta, 0.05, na.rm = TRUE),
            q95=quantile(grundvattenniva_m_u_markyta, 0.95, na.rm = TRUE))->data_minmax_lod

data_complete_logger%>%
    mutate(month=month(date), year=year(date))%>%
  group_by(ID,year)%>%
  summarize(min_level=min(median_level, na.rm=T),
            max_level=max(median_level, na.rm=T),
            q05=quantile(median_level, 0.05, na.rm = TRUE),
            q95=quantile(median_level, 0.95, na.rm = TRUE))->data_minmax_logger

#Hitta överlapp mellan lod och logger och använd bara logger data för den tiden.
row.names(data_minmax_lod)<-paste(data_minmax_lod$ID, data_minmax_lod$year)
row.names(data_minmax_logger)<-paste(data_minmax_logger$ID, data_minmax_logger$year)
duprows <- rownames(data_minmax_lod) %in% rownames(data_minmax_logger)

#Sortera månaderna i rätt ordning
rbind(data_minmax_logger%>%mutate(metod="logger"),data_minmax_lod[!duprows,]%>%mutate(metod="klucklod"))%>%
  select(ID, metod,year, min_level, max_level, q05, q95)%>%arrange(ID, year) ->data_minmax

#Använd bara lodade data om det finns en observation varje monat, dvs 12 månatliga värden.

#data_monthly %>% full_join(data_annual)%>%full_join(data_minmax) %>% group_by(ID, year)->data_all 

data_monthly%>%full_join(data_annual) %>%full_join(data_minmax)%>% 
  mutate(q05=case_when(is.na(median_level_annual)~NA_real_,
                       TRUE~q05),
         q95=case_when(is.na(median_level_annual)~NA_real_,
                       TRUE~q95))%>%
  select(-c(min_level, max_level))%>%
                       pivot_longer(cols=c(januari:q95), values_to="variable")->data_all
```

```{r}
last_year<-2023
```


```{r}
start_time<-Sys.time()
data_all%>%filter(year<=last_year)%>%
  arrange(ID, name, year) %>% 
  drop_na(variable)%>%
  group_by(ID, name)%>%filter(n()>5)%>%
    nest(data = c(-ID, -name)) %>% 
    mutate(fit = future_map(data, 
                            possibly(~ gam(formula = variable ~ s(year, k=n_distinct(.x %>% filter(!is.na(variable)) %>% .$year)-2),
                                data = .x, 
                                method="REML", select=T
                                ), otherwise = NA_real_), .progress = T),
           fderiv = map2(fit, data, possibly(~ derivatives(object=.x, type="forward", select = "s(year)", interval="confidence", level=0.95, data = .y), otherwise = NA_integer_))) %>% 
  mutate(trend = map2(fit, data, possibly(~ predict.gam(object = .x, newdata = .y, type="response"), otherwise = NA_real_), .progress = TRUE)) ->test_gam #Tar ca 15 minuter. 

test_gam%>%filter(!is.na(fit))%>%
    mutate(fderiv = map(fderiv, ~tibble(deriv = .x$.derivative, deriv_se = .x$.se, lower=.x$.lower_ci, upper=.x$.upper_ci))) %>%
  unnest(c(data, trend, fderiv))%>%dplyr::select(-c(fit))%>%
  ungroup()%>%
  mutate(dir=case_when(lower>0 ~1,
                       upper <0 ~-1,
                       TRUE~0))->
  gam_models_grundvatten_nivå
  gam_models_grundvatten_nivå$trend = gam_models_grundvatten_nivå$trend %>% as.vector()
end_time<-Sys.time()

```

```{r}
gam_models_grundvatten_nivå%>%full_join(data_all%>%filter(year<last_year))->for_plots
```
```{r}
data_all%>%filter(year<=last_year)%>%
  arrange(ID, name, year) %>% 
  drop_na(variable)%>%
  group_by(ID, name)%>%filter(n()>2 & n()<6)->korta_serier

gam_models_grundvatten_nivå<-bind_rows(gam_models_grundvatten_nivå, korta_serier)
```



```{r}
data_all %>% 
  filter(year<= last_year)%>%
  drop_na(variable)%>%
  group_by(ID, name)%>%filter(n()>5)%>%
  #filter(n_years >= 10, !is.na(mean_level_month)) %>% 
  nest(data = c(-ID, -name)) %>% 
  mutate(fit = map(data, possibly(~suppressMessages(rkt(date = as.data.frame(.x)$year,  # tar drygt 2 minuter
                                       y=as.data.frame(.x)$variable, correct = TRUE)), otherwise=NA_real_)),
         tidy = map(fit, possibly(~rkt_out(.x), otherwise=NA_real_))) %>% 
  unnest(tidy) %>% 
  dplyr::select(-data, -fit) %>% 
  mutate(sig.stars=cut(p.value, breaks=c(1, 0.05,0.01,0.001,0.0001,0), 
                   labels=c("ns","*","**","***","****") %>% rev, ordered_result = T),
         p.value = p.value %>% round(4),
         slope = slope %>% round(4), 
         tau = tau %>% round(4)) %>% 
         replace_na(list(sig.stars="****")) -> 
  grundvattennivå_mannkendall1
```

```{r}
data_all %>% 
  filter(year<= last_year & year>last_year-6)%>%
  drop_na(variable)%>%
  group_by(ID, name)%>%filter(n()>5)%>%
  nest(data = c(-ID, -name)) %>% 
  mutate(fit = map(data, possibly(~suppressMessages(rkt(date = as.data.frame(.x)$year,  # tar drygt 2 minuter
                                              
                                       y=as.data.frame(.x)$variable, correct = TRUE)), otherwise=NA_real_)),
         tidy = map(fit, possibly(~rkt_out(.x), otherwise=NA_real_))) %>% 
  unnest(tidy) %>% 
  dplyr::select(-data, -fit) %>% 
  mutate(sig.stars=cut(p.value, breaks=c(1, 0.05,0.01,0.001,0.0001,0), 
                   labels=c("ns","*","**","***","****") %>% rev, ordered_result = T),
         p.value = p.value %>% round(4),
         slope = slope %>% round(4), 
         tau = tau %>% round(4)) %>% 
         replace_na(list(sig.stars="****")) -> 
  grundvattennivå_mannkendall6
```


```{r}
data_all %>% 
  filter(year<= last_year & year>last_year-12)%>%
  drop_na(variable)%>%
  group_by(ID, name)%>%filter(n()>5)%>%
  nest(data = c(-ID, -name)) %>% 
  mutate(fit = map(data, possibly(~suppressMessages(rkt(date = as.data.frame(.x)$year,  # tar drygt 2 minuter
                                              
                                       y=as.data.frame(.x)$variable, correct = TRUE)), otherwise=NA_real_)),
         tidy = map(fit, possibly(~rkt_out(.x), otherwise=NA_real_))) %>% 
  unnest(tidy) %>% 
  dplyr::select(-data, -fit) %>% 
  mutate(sig.stars=cut(p.value, breaks=c(1, 0.05,0.01,0.001,0.0001,0), 
                   labels=c("ns","*","**","***","****") %>% rev, ordered_result = T),
         p.value = p.value %>% round(4),
         slope = slope %>% round(4), 
         tau = tau %>% round(4)) %>% 
         replace_na(list(sig.stars="****")) -> 
  grundvattennivå_mannkendall12
```

```{r}
grundvattennivå_mannkendall1%>%mutate(Period="Hela perioden")%>%full_join(grundvattennivå_mannkendall6%>%mutate(Period="6"))%>%full_join(grundvattennivå_mannkendall12%>%mutate(Period="12"))%>%ungroup()->grundvattennivå_mannkendall
```

```{r echo=FALSE, fig.height=25, fig.width=20, message=FALSE, warning=FALSE}
#gam_models_grundvatten_nivå %>%  
  
for_plots%>%
  #filter(name == "april", as.numeric(ID)>158551 & as.numeric(ID)<252423) %>% 
  filter(name == "min_level", as.numeric(ID)==116517) %>% 
  
  ggplot(aes(x=year, y=variable, col=metod))+ 
  geom_line(linetype="dashed")+ 
 facet_wrap(~ID, scales = "free_y", ncol = 8)+
 geom_line(aes(y=trend), linetype="solid")+ 
 labs(title="Nivå-April") +
  scale_x_continuous(breaks = scales::pretty_breaks())+
  theme_classic()

for_plots%>%
  #filter(name == "april", as.numeric(ID)>158551 & as.numeric(ID)<252423) %>% 
  filter(name == "median_level_annual", as.numeric(ID)==158104) %>% 
  ggplot(aes(x=year, y=variable, col=metod))+ 
  geom_line(linetype="dashed")+ 
  geom_line(aes(y=trend), linetype="solid")+ 
  geom_line(data=for_plots%>%filter(name=="max_level", as.numeric(ID)==158104), aes(y=variable), linetype="dashed")+
  geom_line(data=for_plots%>%filter(name=="max_level", as.numeric(ID)==158104), aes(y=trend), linetype="solid")+
  geom_line(data=for_plots%>%filter(name=="min_level", as.numeric(ID)==158104), aes(y=variable), linetype="dashed")+
  geom_line(data=for_plots%>%filter(name=="min_level", as.numeric(ID)==158104), aes(y=trend), linetype="solid")+
 facet_wrap(~ID, scales = "free_y", ncol = 8)+
 #labs(title="Max") +
  scale_x_continuous(breaks = scales::pretty_breaks())+
  theme_classic()



gam_models_grundvatten_nivå %>% 
  filter(name == "minimum_level_annual") %>% 
  ggplot(aes(x=year, y=variable))+ 
  geom_line(linetype="dashed")+ 
 facet_wrap(~platsbeteckning, scales = "free_y", ncol = 8)+
 geom_line(aes(y=trend), linetype="solid")+ 
 labs(title="Minimum annual") +
  scale_x_continuous(breaks = scales::pretty_breaks())+
  theme_classic()
```

```{r}
data_complete_lod%>% select(ID, year)%>%group_by(ID, year) %>% count%>%
  mutate(count=case_when(n==12 ~ "12",
                         n>8 & n<=11 ~"9-11",
                         n<=8 ~"<9")) -> heat_data
colnames(heat_data)[which(names(heat_data) == "year")] <- 
  "year"


ggplot(heat_data, aes(x = year, y = ID, fill = n)) +
  geom_tile() +scale_fill_gradient(high = "darkgreen", low = "white", limits = c(0,NA)) +
  labs(title = "Antal observationer av järn per station och år",
       x = "År",
       y = "Station") +
  theme_minimal()

ggplot(heat_data, aes(x = year, y = ID, fill = as.factor(count))) +
  geom_tile() +
  #scale_fill_gradient(high = "darkgreen", low = "white", limits = c(0,NA)) +
  labs(title = "Antal observationer per station och år",
       x = "År",
       y = "Station") +
  theme_minimal()

```

